### ISSUE TITLE
function: inpaint_background_and_modify_merged_mask

### ISSUE THREAD

**Issue by ByChelsea** [codeslake/SYNDOF#8]
Hi, Lee. Thanks for your great work!

When I read the code, I didn't quite understand the function [inpaint_background_and_modify_merged_mask](https://github.com/codeslake/SYNDOF/blob/255d626312c646bf69086c6e3481064a19f5ae4a/blur_by_depth.m#L66). Is this intend to prevent the color of the focus area from spilling over into the foreground and background? Could you please briefly explain the purpose of this function? Thank you!

By the way, I guess there's a condition missing [here](https://github.com/codeslake/SYNDOF/blob/255d626312c646bf69086c6e3481064a19f5ae4a/blur_by_depth.m#L64). Because it might also need `inpaint_flag` to be True.

Thanks again and looking forward to your reply!

**Comment by codeslake** [comment]
Hi, @ByChelsea.
It took me some time to review the code as it has been a while since I developed this code.

1. The `inpaint_background_and_modify_merged_mask()` function is to handle occluded regions, especially when foreground plane has larger CoC than the background CoC. In the function, we first compute [a mask to inpaint](https://github.com/codeslake/SYNDOF/blob/255d626312c646bf69086c6e3481064a19f5ae4a/blur_by_depth.m#L302), then [inpaint the merged image](https://github.com/codeslake/SYNDOF/blob/255d626312c646bf69086c6e3481064a19f5ae4a/blur_by_depth.m#L312) leveraging the mask. You may want to visualize each step for better understanding.
2. `inpaint_flag` is not used in the code. The flag is from the legacy code. As inpainting is needed after we reach the focused plane (*i.e.* when CoC is 0), the [current condition](https://github.com/codeslake/SYNDOF/blob/255d626312c646bf69086c6e3481064a19f5ae4a/blur_by_depth.m#L64) is enough.

Best,

**Comment by ByChelsea** [comment]
Thank you very much for your reply after reviewing the code!
I know this is very troublesome, I hope I didn't particularly disturb you.

I don't really understand this sentence: “The function is to handle occluded regions, especially when foreground plane has larger CoC than the background CoC”. What's occluded regions and what happens if the foreground has larger CoC than the background?

**Comment by codeslake** [comment]
No worries!

Imagine a center plane (in terms of depth of a scene) is focused.
If the focused plane is occluded by foreground planes that are placed at the front of the focused plane, we need to inpaint the occluded region of the focused plane, as the foreground planes will be blurred and the blurred region requires information from the occluded region.

**Comment by ByChelsea** [comment]
_"the foreground planes will be blurred and the `blurred region` requires information from the `occluded region`"_, from my understanding, `blurred region` refers to the foreground planes and `occluded region` refers to the focused plane. Why does the blurring of the foreground require information about the focused plane? Aren't they independent?

**Comment by codeslake** [comment]
When the foreground plane is blurred, the portion of the occluded region (or even the whole region) becomes visible.

I attach the extreme case in the following. You can see through the focused person originally occluded by a handrail.
![KakaoTalk_20220712_150755450](https://user-images.githubusercontent.com/17451333/178420631-4e6ec29e-36b3-4435-8c3a-d6e94b6ece5e.jpg)

**Comment by ByChelsea** [comment]
Ah, I see. That's a very intuitive explanation, thank you!

In fact, I thought that was the problem at first. [link](https://github.com/codeslake/SYNDOF/issues/5#issuecomment-1107793874) So does the code need to be tweaked a bit?

**Comment by codeslake** [comment]
[These lines](https://github.com/codeslake/SYNDOF/blob/255d626312c646bf69086c6e3481064a19f5ae4a/blur_by_depth.m#L320-L323) are required, as we wand inpainted result to be normalized, otherwise, there will be unnatural seam around the inpainted regions.

**Comment by ByChelsea** [comment]
I see, thanks for your reply.
